{% set name = "fundamentals" %}
{% set version = "2.7.3" %}
{% set python_min = "3.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fundamentals-{{ version }}.tar.gz
  sha256: 9fae69920e9092e47c7f1bd05962bc974ab86c0035ad2bb1acf99ac088f54940

build:
  number: 0
  noarch: python
  entry_points:
    - mysqlSucker=fundamentals.mysql.directory_script_runner:main
    - yaml2db=fundamentals.mysql.yaml_to_database:main
    - sqlite2mysql=fundamentals.mysql.sqlite2mysql:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - wheel
    - setuptools
  run:
    - python {{ python_min }}
    - docopt
    - future
    - psutil
    - python-dateutil
    - pyyaml
    - requests
    - python-daemon

test:
  imports:
    - fundamentals
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/thespacedoctor/fundamentals
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: Some fundamental tools required by most self-respecting python-packages bundled in one place. Very opinionated project setup tools including logging, plain-text settings files and database connections.
  doc_url: https://fundamentals.readthedocs.io
  dev_url: https://github.com/thespacedoctor/fundamentals

extra:
  recipe-maintainers:
    - thespacedoctor
